### ISSUE TITLE
Could not resolve type name: Sitecore.Data.DefaultDatabase, Sitecore.Kernel

### ISSUE THREAD

**Issue by saberone** [pbering/Socker#2]
When I create a clean Sitecore site using the Sitecore Instance Manager tool using version 8.1 revision 160519. I get the following message after I build the solution.

```
Could not resolve type name: Sitecore.Data.DefaultDatabase, Sitecore.Kernel (method: Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).
```

So could it be that the Sitecore Kernel that's included by the solution has different dependencies than a clean 8.1 deployment.

**Comment by pbering** [comment]
Hi, you can see the kernel version used in https://github.com/pbering/Socker/blob/master/src/WebApp/packages.config.

But why is it that you are using SIM for this? The Sitecore instance is running inside the Docker container and you update by just building the solution...

**Comment by saberone** [comment]
Good point. I interpreted the "Place Sitecore "Data" and "Website" folders in /docker/sitecore-*/Sitecore" as put an existing Website  in the Website folder. So what I basically did is create a new instance with SIM and copied databases and the content of the inetpub/Website folder.

But maybe you can clearify that.

**Comment by pbering** [comment]
Agreed and thank you for your feedback, I've clarified that part now :)

**Comment by amith2017** [comment]
I had also the same issue, and I put the all App_config files in the new instance, But it shows the same issue.
Also, I had to face the issue: 

`Could not resolve type name: Sitecore.Pipelines.Loader.InitializeJSNLog, Sitecore.Kernel (method: Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).`

> [Exception: Could not resolve type name: Sitecore.Pipelines.Loader.InitializeJSNLog, Sitecore.Kernel (method: Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).]
>    Sitecore.Diagnostics.Error.Raise(String error, String method) +108
>    Sitecore.Configuration.Factory.CreateType(XmlNode configNode, String[] parameters, Boolean assert) +230
>    Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +41
>    Sitecore.Configuration.Factory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +100
>    Sitecore.Configuration.Factory.CreateObject(XmlNode configNode, Boolean assert) +39
>    Sitecore.Pipelines.CorePipelineFactory.GetObjectFromType(String type, XmlNode processorNode) +66
>    Sitecore.Pipelines.CorePipelineFactory.GetProcessorObject(XmlNode processorNode) +86
>    Sitecore.Pipelines.CoreProcessor.GetMethod(Object[] parameters) +129
>    Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +228
>    Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +158
>    Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +64
>    Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args) +50
>    Sitecore.Nexus.Web.HttpModule.Application_Start() +156
>    Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +450
>    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +534
>    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
>    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +352
>    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296
> 
> [HttpException (0x80004005): Could not resolve type name: Sitecore.Pipelines.Loader.InitializeJSNLog, Sitecore.Kernel (method: Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).]
>    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9947380
>    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
>    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

What are the solutions to this particular issue?
I upgrade 8.0 to 8.1 initial release version.

**Comment by pbering** [comment]
Hi, you should look into using https://github.com/pbering/SockerVS2017 (also a bit outdated). The most current images can be build from here: https://github.com/sitecoreops/sitecore-images.
