### ISSUE TITLE
Missing step in the "Using another sitecore version" section of readme

### ISSUE THREAD

**Issue by tarmo-t** [pbering/Socker#4]
This is awesome example, thanks. Finally got it working by doing this missing step below.

The readme needs one more step to make another version of sitecore work, otherwise a runtime error occurs.

Replace "/src/WebApp/bin/sitecore.kernel.dll" with the sitecore.kernel.dll from Sitecore 8.2 rev. 160729.zip

**Comment by pbering** [comment]
No not manually, you need to update the "Sitecore.Kernel.NoReferences" package to the version that you wish to use.
