### ISSUE TITLE
connection to SQL Server

### ISSUE THREAD

**Issue by ghost** [pbering/Socker#5]
Hi,
I keep getting this error message:
[B44A9735170A] 21:37:52 [ERR] [MPT#6 ] Sitecore.Eventing.EventProvider: Exception processing remote events from database: coreException: System.Data.SqlClient.SqlException
Message: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
Source: .Net SqlClient Data Provider

Do you have any ideas about what could be causing the problem? @pbering

**Comment by pbering** [comment]
Hi, you should add this line https://github.com/pbering/SockerVS2017/blob/master/src/WebApp/Dockerfile#L9, this will make Windows to not cache DNS lookups too long so it can find the SQL server, also when its only just started.

BTW if you got VS2017 you should look at https://github.com/pbering/SockerVS2017 which uses the new Docker integration :)

**Comment by ghost** [comment]
Hi @pbering 7

I reinstalled Docker for Windows and now it works. Apparently it was an issue in my environment.
Thanks for a great project. I'm a fan!

Best,
Bilal
